#! /bin/python
import os


vars = Variables()
vars.Add('no_debug', 'Set to 1 to deactive debug information', 0)

env = Environment(variables = vars)
Help(vars.GenerateHelpText(env))

env['install_path'] = Dir('bin/').abspath


Export('env')

tests = SConscript('sconscript', variant_dir='.build')

